### ISSUE TITLE
Optimize groupby to use dictionary indices

### ISSUE THREAD

**Issue by bmschmidt** [uwdata/arquero#1]
Thanks so much for releasing this project--I've been hoping for precisely this kind of engine for a while. Look forward to using it.

There's some relatively low-hanging fruit for a performance bump on dictionary-encoded columns. (Probably string columns, too, although it's a little trickier.) Currently, `groupby` on a dictionary(utf-8 entries with int32 keys) column is quite slow because--if I'm tracing the code correctly--each individual row is being decoded from utf-8.

[Here's a benchmark counting 2.5 million rows; in this case, it's about 4.7 seconds to count 1,000 distinct fields on character keys and 0.2 seconds on their integer equivalent.](https://observablehq.com/d/6e8361fd74595429)

Similar optimizations should be possible for 'filter' and 'join' on dictionary columns, although there's probably more overhead involved.

**Comment by jheer** [comment]
Thanks! The core engine was written primarily to support vanilla JS arrays and typed arrays, with Arrow support routed through the Arrow JS Table `get` method. I'd be happy to review a PR that better utilizes dictionary indices as long as it does not result in _too_ egregious of a leaky abstraction.

For anyone reading, one place to start digging would be https://github.com/uwdata/arquero/blob/master/src/engine/groupby.js. That said, a more fruitful starting point might be to look at [fromArrow](https://github.com/uwdata/arquero/blob/master/src/format/from-arrow.js) and our very simple [Column abstraction](https://github.com/uwdata/arquero/blob/master/src/table/column.js), and expand those to support an alternative "getter" (`key(row)`?) that would default to providing the same value as `get` but could be configured to return more efficient keys as needed. I'd have to dig more to see what (if anything) might be needed on the Arrow side to make things come together cleanly.

**Comment by bmschmidt** [comment]
Got it; I had been imagining Arrow as a little more fundamental to the design. 

Haven't had a chance to dig in, but It looks to me like the clearest strategy might be to change the keyFunction to work differently on dictionary columns since a key has already been generated. This would work for groupby, but not for filter or join.

My experience with Arrow has been that the text types are so slow that almost any workaround is worthwhile with moderately sized data.

Another option here is to forgo the arrow types entirely and represent text columns (dictionary *and* character) as native javascript arrays of strings. This adds some overhead at table creation since you lose the zero-copy benefits of arrow, but you gain the time back on the very first groupby operation--in my benchmark, it takes 1 second, just about the geometric mean of the other two methods, but should also be faster for joins and filters. 
https://observablehq.com/d/6e8361fd74595429

One simple but kinda ugly fix would be an option on aq.fromArrow(table, {unpack_dictionaries: true}) to do this at load time, which will accelerate later queries but cost:

1. Extra memory.
2. About a second per few million rows at load time.

**Comment by jheer** [comment]
Thanks for the benchmark info. I had also noticed that Arrow string access was slow, but I did not appreciate just how much.

I had a similar idea earlier regarding an "unpack" option for `fromArrow()`. Arrow columns include a `toArray` method which in theory could handle the conversion for us. One nice thing about that method is that it uses zero-copy `subarray` calls if the backing data is just a normal typed array. However, perusing the Arrow code it also seems that the method currently bypasses `null` checks (in contrast, the column `get` method gets overridden to check the null value bitmaps if a column has any null values). So I decided to hold back until we can confirm whether or not `toArray` will return the "correct" arrays (nulls and all).

If nothing else, Arquero could perform the null checks itself, use the `toArray` route when there are no nulls, and use slower iterative calls to `get` when there are.

**Comment by jheer** [comment]
I released a new version (0.2.0) that adds an `unpack` option for `fromArrow`. A corresponding notebook with an example is here: https://observablehq.com/@uwdata/arquero-and-apache-arrow

I'll leave this issue open to track internal support for efficient use of dictionary types.

**Comment by bmschmidt** [comment]
Awesome, thanks.

You're right, arrow's toArray() methods ignore null masks for some primitive types (float, int32) where it simply transfers back the array. And for dictionaries and strings, toArray() seems to be simply [a wrapper around get](https://github.com/apache/arrow/blob/abc786099627ef429109da16b9dc768b4efbd866/js/src/visitor/toarray.ts#L103), so no benefit to using it.

There is one major improvement in unpacking possible just for dictionaries. All these methods still do a utf-8 decode for each occurrence of an entry, but it's possible to just decode the master dictionary at the start and fill it in. If there are only a few dictionary codes, this can be 50-100x faster. [Demonstration function at observable](https://observablehq.com/@bmschmidt/faster-arrow-dictionary-unpacking). If I can get yarn working, I'll try to bundle it as a pull request.

**Comment by bmschmidt** [comment]
[I put up this change on a fork](https://github.com/bmschmidt/arquero/commit/c02318ab5f1690a4aed54f571e49bace6e86285c), but I'm not sure how to test it without adding arrow as a dev dependency.

An in-between solution that would also make a lot of sense is to extend arrow's dictionary class to memoize the dictionary strings, while still using the underlying arrow columns for keys. Here's a monkey patch that does it.

```javascript
function bless_getter_with_cache(col) {
  if (!col.dictionary) {return}
  if (!col._materialized_dictionary) {
    col._materialized_dictionary = [] 
  }
  col.get = function(i) {
   const ix = col.indices.get(i);
   if (ix === null) {return ix}
   return col._materialized_dictionary[ix] !== undefined ? 
     col._materialized_dictionary[ix] : 
     col._materialized_dictionary[ix] = col.dictionary.get(ix)
  }
}
```

**Comment by domoritz** [comment]
@bmschmidt would it make sense to submit a patch to arrow to speed up dictionaries? Or does the patch make specific assumptions that don't hold in general?

**Comment by jheer** [comment]
I had the same reaction as @domoritz, see also my comment on https://github.com/bmschmidt/arquero/commit/c02318ab5f1690a4aed54f571e49bace6e86285c.

**Comment by bmschmidt** [comment]
You are both right that this is really an Arrow issue. I'll see about raising an issue there. The main reason that it might not fit there is that it increases memory overhead by a somewhat unpredictable amount, and one benefit of Arrow is predictable, low memory usage.

FTR, my impression from the discussion boards there is that the JS branch of arrow does not have a great deal of momentum, and the two choices of typescript for development and JIRA for issue tracking increase the friction for community involvement a bit. (I don't know how to write this patch in typescript! Although I guess I could learn) One reason I'm excited about arquero is that it demonstrates how useful the JS implementation actually is.

**Comment by jheer** [comment]
I spent more time thinking about accessing Arrow dictionary keys directly as part of the `groupby` or `hash-join`  / `lookup` logic. While possible, this is complicated by the fact that Arquero supports not just direct column values, but arbitrary formulas over those column values. In the case of `groupby` expressions, aggregate calculations are also permitted! Augmenting Arquero to access dictionary keys when available but not when arbitrary expressions are supplied incurs (IMHO) a poor cost-to-benefit ratio relative to other possible approaches. As a result I don't plan to add direct dictionary key access and am closing out this issue. Instead, I think it would be ideal for Arrow to support more efficient unpacking / caching of extracted string values.

**Comment by jheer** [comment]
So I had a change of heart here: Arquero v0.9.0 now includes optimized dictionary unpacking (thanks @bmschmidt!). Given the significant performance improvement for a relatively small amount of extra code, plus the slow pace of Arrow JS development, this seems to have a good cost/benefit ratio. We can always simplify later if Arrow JS rolls out a more performant `toArray` implementation for dictionary columns in the future.
