### ISSUE TITLE
Access a column programmatically on a table expression

### ISSUE THREAD

**Issue by john-guerra** [uwdata/arquero#10]
Apologies if this shouldn't be an issue, but I have been searching everywhere and haven't been able to understand what can I do with table expressions. Is this documented?

I want to derive columns programmatically. I have a dataset with a bunch of dates per each row, and I want to compute their relative position compared to a reference one. I know I can do:
```
dt.derive({
  date1_rel: d => d.date1 - d.date_ref,
  date2_rel: d => d.date2 - d.date_ref,
 ...
})
```

But I don't want to write that by hand. I tried then these cells on Observable:

```
columnFechas = [
  "fis",
  "fecha_de_muerte",
  "fecha_reporte_web"
  "fecha_recuperado",
  "fecha_de_notificaci_n",
  "fecha_diagnostico"
]
```

```
deriveFechas = Object.fromEntries(
  columnFechas.map(f => [
    `${f}_res`,
    d =>  d[f] - d.fecha_reporte_web 
  ])
)
```

```
dt.derive(deriveFechas)
```

But It throws an error saying `Invalid column "f": "d[f]"`. I tried debugging the code and noticed that the function is a table expression, so for a reason I don't understand I cannot even console.log the attribute d. *How do I get the column that is in the variable `f` in a table expression*. Documenting this could be important whenever you have column names with spaces

Here is a notebook replicating the issue

https://observablehq.com/d/2783d075d8079564#fechas
 
Seems related to #5, is there a way of doing `op.get(column, d)`?

**Comment by jheer** [comment]
I believe the issue is that you are creating closures (it should not be due to spaces in column names). Arquero will re-parse the table expression and the enclosing scope for `f` is lost.

However, Arquero table expressions don’t have to be function objects, they can also be code strings. If instead of a closure you generate a string with your variable name included it should work.

Something like:

```
`d =>  d[“${f}”] - d.fecha_reporte_web`
```

**Comment by jheer** [comment]
p.s. I plan to add a dedicated page on table expressions to the API docs, I just haven't gotten around to it yet!

**Comment by jheer** [comment]
Added initial table expression documentation at https://uwdata.github.io/arquero/api/expressions

**Comment by john-guerra** [comment]
This is awesome Jeff, thanks for all the great work! Let me know if I can be of any help

**Comment by john-guerra** [comment]
BTW the new documentation for expression looks amazing! How can you do this so quickly?!

**Comment by arvind** [comment]
A question I continue to ask myself despite years of working with Jeff (perhaps with even more question marks now that I’m a faculty member as well :)
