### ISSUE TITLE
Version 4.0.0 removes op.values

### ISSUE THREAD

**Issue by john-guerra** [uwdata/arquero#116]
If you are like me and were using *op.values* to assign default values, version 4.0.0 will break your code.

e.g.

~~~js
df
  .pivot(
    "date",
    { value: d => (op.values(d.grade).length ? op.sum(d.grade) : "") },
    { sort: false }
  )
~~~

Will fail throwing * Error: Invalid column reference (must be input to an aggregate function): "d.grade"*

**Solution(?)**

Use *op.array_agg* instead

~~~js
df
  .pivot(
    "date",
    { value: d => (op.array_agg(d.grade).length ? op.sum(d.grade) : "") },
    { sort: false }
  )
~~~

Leaving this here in case anyone else face the same problem.

**Comment by jheer** [comment]
https://github.com/uwdata/arquero/releases/tag/v4.0.0 😬
