### ISSUE TITLE
How to left pad a string for a new column?

### ISSUE THREAD

**Issue by clhenrick** [uwdata/arquero#12]
For example, in the case when dealing with U.S. Census FIPS values that are stored as numbers in a dataset, how would I convert the numeric values back to string values that are left padded with the correct number of zeros?

When I try doing something like:

```js
table.derive({
  "fips_state_str": d => `${d.fips_state}`.padStart(2, "0")
})
```

... Arquero throws an error. Looking at the API documentation and docs on Observable I don't see an example of how to accomplish this, but apologies if I missed or overlooked something. Thanks!

**Comment by clhenrick** [comment]
Follow up, I was able to add a utility function to accomplish this:

```js
  aq.addFunction(
    "leftPad",
    (value, times, char) => `${value}`.padStart(times, char)
  );
```

and use it as follows:

```js
table.derive({
  "fips_state_str": d => op.leftPad(d.fipsstate, 2, "0")
})
```

Though I'm still curious if this is the recommended approach and if Arquero has a built in  method for handling this.

**Comment by jheer** [comment]
Thanks! Arquero currently lacks padding methods as part of the "built-in" functions, but adding `padstart` and `padend` (or similar) would be straightforward. I'll look into adding those soon. In the meantime, your use of the `addFunction` method is spot on.
