### ISSUE TITLE
Should 'table.sample' also shuffle?

### ISSUE THREAD

**Issue by bmschmidt** [uwdata/arquero#127]
I often use `sample` with fraction '1' in `dplyr` or `pandas` to shuffle a (grouped?) table in place. This doesn't work in arquero, which just returns the table in the same order. Relatedly, I was surprised that table.sample, especially without replacement, rarely returns the rows in random order even when the fraction is less than 1. I had been treating it as though it did, since for small fractions the reservoir sampling method produces an ordering that looks random to the naked eye. 

Of course you don't promise it does shuffle! But I wouldn't be surprised if others would also assume that 'sample' returns random order as well as random rows; and if you did that that in, say, an experimental design context, it could cause some headaches. Would it be a huge hit to just toss a Fischer-Yates shuffle at the end of the existing sample methods, perhaps with a 'disable' option?

**Comment by jheer** [comment]
Yes, you're right that there is no guarantee of shuffling. When the fraction is `1` under sampling without replacement, Arquero even optimizes the "sampling" by bulk copying row indices for a group. Reservoir sampling starts by filling the reservoir with the first _k_ samples, so for larger fractions / reservoir sizes you'll largely see that ordering. Meanwhile, the weighted sampling without replacement method is more likely to draw higher weights and so I would expect that to affect the ordering (and whether this is good or bad may vary on use case and expectations...). On top of all that, when performing stratified sampling after `groupby()`, the resulting table is in any case firstly ordered by group.

There are a few aspects to consider:

1. Should `sample` worry about this at all? Perhaps there should be a `shuffle()` verb instead to keep the API design "orthogonal"? (Though admittedly one can already do this in a round-about way by creating a random value column and ordering by that.) Still, there are efficiency gains to be had by combining shuffling and sampling, especially given that the `sample()` verb reifies its output - so I'm not adverse to adding a `shuffle` option to the `sample()` verb.
2. There is also the question of how groups should be handled. Should we shuffle within groups by default, or across the full table? Do we need to provide more nuanced options to control this? (Also noting that `orderby()` does not auto-magically consider `groupby()` keys, those have to be passed to `orderby()` explicitly to be considered.)

Happy to hear people's thoughts on these questions.

**Comment by jheer** [comment]
PR #128 takes a simple approach to this issue. It adds a `shuffle` option (default `true`) to the `sample()` verb to ensure randomized row orders across the entire output table. Does this suffice? If group-level shuffling is later needed, we could expand the option in the future to also accept more specific string values, such as `'group'` or `'table'`.

**Comment by bmschmidt** [comment]
Thanks! That's just what I would have liked.

I cannot think of a reasonable case where group-level shuffling would be desirable.

**Comment by jheer** [comment]
Released in v4.1.0.
