### ISSUE TITLE
Question: how to drill to underlying data after rollup

### ISSUE THREAD

**Issue by OlegZee** [uwdata/arquero#129]
Well, I have a table
```javascript
const tableWithGroups = _data
  .filter((d: any) => d.AGEQ100 === 65)
  .groupby('NIVGEO', 'CODGEO')
  .orderby(aq.desc('NIVGEO') as any, aq.desc('CODGEO') as any); // this does not work with partitions
```
and a result table:
```javascript
const resultTable = tableWithGroups
  .rollup({
    libgeo: op.any('LIBGEO'),
    count: op.count(),
    sum: op.sum('NB'),
    min: op.min('NB'),
    max: op.max('NB'),
} as any)
  .orderby(aq.desc('NIVGEO') as any, aq.desc('CODGEO') as any);
```
Now I want to implement a function (in my system) that for each row in `resultTable` would return underlaying data records.

I can access partitions in such way:
```javascript
const groups = tableWithGroups.partitions(true).map(data => _data.reify(data));
```
but I don't see how to find proper partition for each row in resultTable.

Questions:
1. please give me a hint how to access it. Can I, say, implement custom op to get indices of the underlying data?
2. why partitions are not sorted (so that I cannot match them with original data by index?

**Comment by jheer** [comment]
Interesting question! I wrote up my response in a notebook:
https://observablehq.com/@uwdata/arquero-roll-up-and-drill-down

Take a look and please post here if you have any follow-up questions or suggestions.
