### ISSUE TITLE
Make aggregates ordering sensitive.

### ISSUE THREAD

**Issue by vorbei** [uwdata/arquero#130]
For a table and query like follows:

```javascript
aq.from([
    { a: 2, i: 4 },
    { a: 1, i: 5 },
    { a: 3, i: 3 },
    { a: 4, i: 2 },
    { a: 5, i: 1 }
  ])
  .orderby('a')
  .derive({
    agg: d => op.array_agg(d.a)
  })
```

Currently, agg will output in the original order: [2,1,3,4,5], however, after ordering the table, the aggregated array should follow the order, or at least offer an 'ordered' option.

**Comment by vorbei** [comment]
If I add a '.reify()' after 'orderby', the aggregated array will output the expected result.

**Comment by jheer** [comment]
Yes, right now aggregates scan the data in the physical order, regardless of the `orderby` settings. We can update the aggregate scan logic to use sorted row indices. One question is if we want to include additional aggregate operator metadata, indicating if an operator is order sensitive (thus allowing optimization), but that could be added later if desired.
