### ISSUE TITLE
Optimize antijoin / semijoin performance.

### ISSUE THREAD

**Issue by ericemc3** [uwdata/arquero#136]
Comparing baby names given to boys and girls, i failed running a semijoin (2 minutes after 'notebook not responding' message),
while a simple join takes only 1 second
```
  //baby names by year
  let url = "https://static.data.gouv.fr/resources/jeux-de-donnees-de-formation/20210319-095108/prenoms-nat2019.csv"

  let dt = await aq.loadCSV(url, {delimiter:';'})
  
  // babynames for boys
  let t1 = dt.groupby('preusuel')
             .filter(d => d.sexe == '1')
             .rollup({nombre_1: op.sum('nombre')})  // 16661 rows
  
  // babynames for girls
  let t2 = dt.groupby('preusuel')
             .filter(d => d.sexe == '2')
             .rollup({nombre_2: op.sum('nombre')}) // 19784 rows

  //return t1.semijoin(t2)  // 2 mn
  
  return t1.join(t2) // 1 s
```

**Comment by jheer** [comment]
Yes, right now Arquero's join implementation supports both hash-join and nested-loop-join algorithms depending on the inputs. The hash-join can be much more efficient when the join predicate only involves matching on key values directly.

The semijoin and antijoin implementations currently use a nested-loop-join algorithm only. Updating these to include a hash-join when applicable is a long-standing TODO, and would greatly speed up your example above. Thank you for reminding me!

**Comment by jheer** [comment]
Fixed in v4.1.3, and also updated on Observable.

**Comment by ericemc3** [comment]
Excellent, thank you, it works perfectly well!

For the record and in relation with #113
i would dream of a SELECT DISTINCT equivalent allowing to simplify my request this way:

```
dt.filter(d => d.sexe == '1').distinct('preusuel')
  .semijoin( dt.filter(d => d.sexe == '2').distinct('preusuel') )
```

**Comment by jheer** [comment]
Would dedupe work for your distinct use case here?

**Comment by ericemc3** [comment]
You are right, thank you! Not used yet to dedupe(). This works fine:

```
  let t1 = dt.filter(d => d.sexe=='1')
             .dedupe('preusuel').select('preusuel')
  
  let t2 = dt.filter(d => d.sexe=='2')
             .dedupe('preusuel').select('preusuel')

  return t1.semijoin(t2)
```
