### ISSUE TITLE
aq.fromCSV's "delimiter"-option is incorrectly documented

### ISSUE THREAD

**Issue by sebastiankienzl** [uwdata/arquero#14]
Hello!

I just tripped over a small inaccuracy: in the [documentation for fromCSV](https://uwdata.github.io/arquero/api/#fromCSV), the option object's property for specifying the delimiter is referenced as _delimiter_, whereas in the respective code it says _delim_:

https://github.com/uwdata/arquero/blob/f4e03ebf0479442d6f940e14a80bf3076975980c/src/format/from-csv.js#L36

Therefore code like `aq.fromCSV(text, { delimiter: ';' })` does not work as intended.

**Comment by jheer** [comment]
Thanks! The documentation is how it is supposed to be. I've pushed a fix and cut a new patch release.
