### ISSUE TITLE
Arquero + Observable: cannot see method under the op.* object with TAB

### ISSUE THREAD

**Issue by dan-reznik** [uwdata/arquero#143]
I am following the instructions in the tutorial to see the methods under the op. object by (i) creating an new observable cell, (ii) typing op. + tab, but nothing pops up.

**Comment by jheer** [comment]
Hmm, this works for me:

1. Go to https://observablehq.com/@uwdata/introducing-arquero
2. Add a new cell
3. Type `op.` and hit tab

I then see an autocomplete menu. I tested this on Chrome and Firefox, both worked -- though on Firefox I didn't need to hit tab.

**Comment by dan-reznik** [comment]
Just tried it again, from scratch as you suggested, no luck, though my two
zoom friends are doing it in theirs and it is working. I am using Chrome.

Dan

**Comment by jheer** [comment]
Hmm. Maybe you have a browser extension or setting that is interfering? Hard to say.

In any case, this is not related to Arquero per se, but how Observable works, and so I'm going to close out this issue.

**Comment by dan-reznik** [comment]
Jeff I am teaching a class to 24 people and would like to use
observable+vega-lite+arquero. However, after having to do the autocomplete
(e.g., for op.*) unsuccessfully in 3 different machines (windows, chrome) I
own, could you recommend someone who could help me debug this? It just
won't work

Dan Reznik
PUC, Rio, Brazil

**Comment by jheer** [comment]
The autocomplete is an Observable feature, not an Arquero feature, so I don’t know precisely how it is implemented or why it works for others but not you. Sorry!

I’d recommend filing an issue with Observable’s support forum, as they are the service providing the autocomplete.

**Comment by dan-reznik** [comment]
Dear Jeff, thanks I sent a msg to the Observable support. This is an issue
that will probably plague many people.

**Comment by dan-reznik** [comment]
Jeff I will be using arquero for a class I am teaching. Do you have
thoughts on other tools on the IDL lab such as Lyra, or Voyager 2?
They seem not to have received any updates in 3-5 yrs.

**Comment by jheer** [comment]
Those are research prototypes, not production-ready systems. And yes, they are not actively developed. So they might be interesting to demo, but I wouldn’t make anyone use them exclusively for any projects.

**Comment by dan-reznik** [comment]
ok. btw, i installed opera, and now i *can* see the methods of op.* and
friends.

one question: having been using the tidyverse for some 5 yrs, why did you
decide not to mirror the name of methods there like mutate(), nest(),
summarize(). did you have copyright concerns?

dan
