### ISSUE TITLE
Improve null handling for op.* functions

### ISSUE THREAD

**Issue by dan-reznik** [uwdata/arquero#144]
I am trying to filter the beer dataset w/ op.includes() as below, but it doesn't work, see the 2nd code snippet.

```
beer
 .filter(d => op.includes(d.style, 'Hefeweizen'))
```

But if I do it like this it works:

```
beer
 .filter(d => op.includes(op.lower(d.style), 'hefeweizen'))
```

i.e., it is requiring me to surround the column name with op.lower()

**Comment by jheer** [comment]
I believe it is failing because `includes` is being invoked on null values of `d.style`. The following (which safeguards against null values) works:

```js
beers
 .filter(d => op.includes(d.style || '', 'Hefeweizen'))
```

We can also consider adding `null` checks internally for some of the op methods.

**Comment by dan-reznik** [comment]
I would urge you to do that internally, because this will be a recurrent
issue.
