### ISSUE TITLE
a nerdy pun: Arquero could also be called R-quero

### ISSUE THREAD

**Issue by dan-reznik** [uwdata/arquero#149]
Per its fortunate inspiration on the tidyverse workflow, many kudos to that. Wonder if the pun is just a happy coincidence

**Comment by jheer** [comment]
Just a happy coincidence... the real origin was <b>ar</b>-ray <b>quer</b>-ies.

**Comment by dan-reznik** [comment]
with so many happy puns u know u r on the right track, congrats!
