### ISSUE TITLE
feature request: aq.fromCSV2()

### ISSUE THREAD

**Issue by dan-reznik** [uwdata/arquero#160]
Many non-US csv's use ";" as separators and "," as decimal markers. Call these "type-2" csv's. In R there are two functions: read_csv() for regular US-style, and read_csv2() for type-2.

Currently one needs to do something like the code below in order read type-2 csv (available on Observable [here](https://observablehq.com/@dan-reznik/importa-csv-brasileiro)):

```
parseColon = v => parseFloat(v.replace(",","."));

table = aq.loadCSV('type2.csv', // could be aq.fromCSV() as well
           { delimiter: ";", parse : { col1: parseColon, col2: parseColon } })
```

so my suggestion is smtg like the above gets wrapped into aq.loadCSV2() and aq.fromCSV2(). It will avoid much rework. Also notice one would not need to list which numeric columns need to be parsed with "parseColon". This logic would be internalized. If a column is deemed numeric, apply the right parsing.

alternatively, you can add "decimal_marker" to the option object in loadCSV() and fromCSV(), defaulting to ".". so the new code would look like

```
table = aq.loadCSV('type2.csv', // could be aq.fromCSV() as well
           { delimiter: ";", decimal_marker: ',' });
```

**Comment by jheer** [comment]
This use case is now supported in Arquero v4.5.0, through the addition of the `decimal` option for `fromCSV` and `loadCSV`. I did not end up adding a shortcut from/loadCSV2 method, but hopefully this helps!

**Comment by dan-reznik** [comment]
Jeff, flattered you did this! Thanks! My students are having a ball w
Arquero! Any chance the request for column rename can be included as well?
that is pretty crucial.

Dan

**Comment by jheer** [comment]
Column rename was already added, use table.rename().
