### ISSUE TITLE
Version 4.4.0+ causes this runtime error: Uncaught ReferenceError: can't access lexical declaration 'Buffer' before initialization

### ISSUE THREAD

**Issue by JeffreyPalmer** [uwdata/arquero#166]
My application builds and runs fine with 4.3.0, but after upgrading to 4.4.0, I now receive this error in the javascript console: 
 
```javascript
Uncaught ReferenceError: can't access lexical declaration 'Buffer' before initialization
```

My app is written in Svelte using TypeScript and Vite (or Snowpack - they both fail with the same error) to build to the final deployable version. 

Happy to provide as much detail as you think is valuable. If I'm doing something obviously wrong, please let me know.

Thanks for the library, btw - I really love using it with d3 for data transformation!

**Comment by jheer** [comment]
I can replicate the issue and confirm that it stems not from Arquero directly, but from Apache Arrow v4.0.0. I will file an issue with the Arrow team. We might have to rollback the dependency to version 3.0.0.

In the meantime, if you find a workaround please share -- if you are not using Apache Arrow parsing or output generation features you might be able to configure your project to simply exclude the Arrow dependency. This is what Arquero does for its default browser build.

**Comment by jheer** [comment]
I've reverted to Apache Arrow v3.0.0 in [v4.6.0](https://github.com/uwdata/arquero/releases/tag/v4.6.0). We can update the dependency once a fixed version of Arrow is released.

**Comment by domoritz** [comment]
Arrow 4.0.1 will fix this issue.
