### ISSUE TITLE
How to aggregate an array of rows?

### ISSUE THREAD

**Issue by ianstormtaylor** [uwdata/arquero#170]
I'm trying to essentially create a nested table, with rows inside rows. For example many different accounts full of stocks. You might want to aggregate new properties at the account level, while still having the `account.rows` filtered/sorted to render each of the holdings (with their own aggregates) as well.

In the docs there are lots of examples of using the `array_agg` functions to create things like:

<img width="276" alt="image" src="https://user-images.githubusercontent.com/311752/117850599-7632c300-b253-11eb-8873-fe5954b1da16.png">

But what if you wanted `rows` to actually contain the subrows themselves instead of just the index? I couldn't find anything like that, and wasn't sure what the recommended approach is.

**Comment by ianstormtaylor** [comment]
Very cool, thanks for the updated example! (Yup, no need for Arquero to do anything smart with the nested rows, I'm just generating a deeply nested table from some relational data and was trying to figure out how to do it tersely.)

It might be cool to add an identity-like operation in the future, so you could do something like `op.array_agg(op.row())` without having to attach the `rows` manually as a column first.

**Comment by jheer** [comment]
A new `op.row_object()` is included in [v4.6.0](https://github.com/uwdata/arquero/releases/tag/v4.6.0). I've also updated the "Roll-Up and Drill-Down" notebook to use it.

**Comment by ianstormtaylor** [comment]
That is awesome, thank you @jheer!
