### ISSUE TITLE
Error with nested `op.sum` calls

### ISSUE THREAD

**Issue by ianstormtaylor** [uwdata/arquero#171]
A non-nested `op.sum` this works:

```tsx
aq.table({ x: [1, 2, 3], y: [4, 5, 6] })
  .rollup({ dot: d => op.sum(d.x * d.y) })
  .view()
```
<img width="749" alt="image" src="https://user-images.githubusercontent.com/311752/117860502-5c4aad80-b25e-11eb-9ebe-82708cb239eb.png">

But if you nest the `op.sum` calls (for example when aggregating a weighted average) it throws:

```tsx
aq.table({ x: [1, 2, 3], y: [4, 5, 6] })
  .rollup({ dot: d => op.sum(d.x * op.sum(d.y)) })
  .view()
```
<img width="747" alt="image" src="https://user-images.githubusercontent.com/311752/117860479-56ed6300-b25e-11eb-8ad7-d0fb3d71db0e.png">

I think this is a bug? (Although I might be doing something stupid!)

**Comment by ianstormtaylor** [comment]
Well, I'm indeed an idiot because I didn't actually need to nest these things to perform the aggregate I wanted.

**Comment by jheer** [comment]
Not a bug, also not stupid! In general, we can't nest aggregation functions as each requires a separate full pass over the data. One approach is to first calculate the marginal sum over y via the `derive` verb, then use that in the subsequent rollup.

```
aq.table({ x: [1, 2, 3], y: [4, 5, 6] })
  .derive({ sum_y: op.sum('y') })
  .rollup({ dot: d => op.sum(d.x * d.sum_y) })
  .view()
```

However, for your specific example, we can rearrange the terms to something mathematically equivalent that is computable in a single pass:

```js
aq.table({ x: [1, 2, 3], y: [4, 5, 6] })
  .rollup({ dot: d => op.sum(d.x) * op.sum(d.y) })
  .view()
```
