### ISSUE TITLE
table.toHTML() default header alignment

### ISSUE THREAD

**Issue by dan-reznik** [uwdata/arquero#175]
Perhaps this is intended, but the alignment of the output's header in the .toHTML() is left while those of the columns is right. Perhaps all should be left?

```{js}
dt = aq.table({
  u: ['a', 'a', 'b', 'b'],
  x: Int32Array.of(1, 2, 3, 4),
  y: Float64Array.of(5, 6, 7, 8)
})

html`${dt.toHTML()}` // produces misaligned table
```

![Screenshot 2021-05-15 07 41 38](https://user-images.githubusercontent.com/16231062/118357543-16893000-b551-11eb-8823-0074ff5c6498.png)

**Comment by jheer** [comment]
Fixed column alignment in 4.7.0.
