### ISSUE TITLE
Add default limit to markdown/html output.

### ISSUE THREAD

**Issue by dan-reznik** [uwdata/arquero#176]
If I load a longish (200k) arrow file, and then attempt to render a few lines as markdown, .toMarkdown() will attempt to render *all* lines, crashing the notebook.

```
flights = aq.loadArrow('https://vega.github.io/vega-datasets/data/flights-200k.arrow')
// this crashes notebook
md`${flights.slice(10).toMarkdown()}`
```

**Comment by jheer** [comment]
You can use the *limit* option to control the number or rows printed. I’ll interpret this as a request to set a reasonable default limit :)

**Comment by jheer** [comment]
Added limits in 4.7.0.
