### ISSUE TITLE
decimal option in aq.loadCSV()

### ISSUE THREAD

**Issue by dan-reznik** [uwdata/arquero#177]
I am thankful there is now an option to specifiy the decimal separator in aq.fromCSV(), already showing up in the documentation for this function. 

Does aq.loadCSV() also accept "decimal" as an option? The docs don't reflect it yet. 

https://uwdata.github.io/arquero/api/#loadCSV

**Comment by jheer** [comment]
Yes, it is supported. As written in the loadCSV docs:
*options*: File loading and CSV formatting options. Accepts the options of both the *load* and *fromCSV* methods, but ignores any settings for the load `as` and `using` options.
