### ISSUE TITLE
aq.from array of arrays and column names

### ISSUE THREAD

**Issue by ericemc3** [uwdata/arquero#194]
I would expect this to work:
`aq.from([ ['d', 4], ['e', 5], ['f', 6] ], ['col1','col2'])`

but i get:
![image](https://user-images.githubusercontent.com/17407796/119345130-c28cf280-bc98-11eb-9490-645f7cf49859.png)

**Comment by jheer** [comment]
From the [`from` documentation](https://uwdata.github.io/arquero/api/#from): for array-valued input the *names* argument "specifies the keys to look up on each row object." So the example above tells Arquero to extract values for the keys `'col1'` and `'col2'`, which are `undefined` for the given arrays, as the valid keys are the array indices `0` and `1`.

Instead, you can build a table from just the array of arrays, followed by a `rename()` verb:

```js
aq.from([ ['d', 4], ['e', 5], ['f', 6] ])
  .rename({ 0: 'colA', 1: 'colB' })
```

**Comment by ericemc3** [comment]
Thank you for the explanation, it makes sense, i'll use a rename, or a Map in that simple 2 columns case:
`aq.from(new Map([ ['d', 4], ['e', 5], ['f', 6] ]), ['col1','col2'])`
