### ISSUE TITLE
feature request: setColumnNames()

### ISSUE THREAD

**Issue by dan-reznik** [uwdata/arquero#195]
Often one will want to change a long list of column names of a table programmatically (e.g., via string processing), and then do a one-shot "renaming". In R this is commonplace (setNames()).

Currently in arquero we have .rename() which does take in an object of arbitrary size; to do the above one could build a suitable (with keys and values) object and pass it to rename.

But a simpler interface to the above another is something like:

```
table.setColumnNames(['newCol1', 'newCol2', ...])
```

And have the new names be applied in order.

**Comment by jheer** [comment]
While adding a new method like `setColumnNames()` makes sense, I wonder if it might be more elegant to build on existing verbs and provide a renaming helper?

For example, an alternative might be something like:

```js
table.rename(setNames('newCol1', 'newCol2'))
```

Where the `setNames()` function is a selection helper that generates a function that takes a table as input and returns a renaming map compatible with `rename()`, `select()`, and any other verb that accepts a selection helper.

```js
function setNames(...names) {
  names = names.flat();
  return table => {
    const m = new Map();
    const n = Math.min(names.length, table.numCols());
    for (let i = 0; i < n; ++i) {
      m.set(table.columnName(i), name);
    }
    return m;
  }
}
```

Thoughts?

**Comment by dan-reznik** [comment]
I honestly like the

table.setNames([ array ])

idiom better, but I am biased (tidyverse)

Dan

**Comment by dan-reznik** [comment]
setColNames([ ... ])
