### ISSUE TITLE
feature request: op.corr() w/ option for spearman correlation

### ISSUE THREAD

**Issue by dan-reznik** [uwdata/arquero#198]
Dear Jeff, any chance that the nicely written logic below could be internalized into op.corr()?

```js
aq.table({
    a: [1, 2, 2, 3, 4, 5],
    b: [9, 8, 8, 7, 6, 5]
  })
  .orderby('a').derive({ ra: op.avg_rank() })
  .orderby('b').derive({ rb: op.avg_rank() })
  .rollup({ rho: d => op.corr(d.ra, d.rb) })
  .view()
```

meaning one could simply say:

```js
aq.table({
    a: [1, 2, 2, 3, 4, 5],
    b: [9, 8, 8, 7, 6, 5]
  })
  .rollup({ corr: d => op.corr(d.a,d.b, {method:"spearman"}) })
  .view()
```

later you could add fancier methods.

**Comment by jheer** [comment]
Thanks for the suggestion! At this point I'm not planning on adding this as part of the "core" Arquero distribution, but it _can_ be added as a custom aggregate function, as described in this notebook: https://observablehq.com/@uwdata/adding-aggregate-functions-to-arquero

In the future, I could imagine creating sets of "add-on" packs to keep the core library relatively lean, but allow for easy registration and sharing of new op functions, aggregate functions, verbs, and so on.
