### ISSUE TITLE
request: please provide example of R^2 calculation in statistics page

### ISSUE THREAD

**Issue by dan-reznik** [uwdata/arquero#199]
Dear Jeff

This [page](https://observablehq.com/@uwdata/arquero-cookbook#statistics) is phenomenal, would be thankful if you could add to sample code for R^2 calculation (dispersion)

**Comment by jheer** [comment]
The basic [R-squared formula](https://en.wikipedia.org/wiki/Coefficient_of_determination) is pretty straightforward, but requires that one has meaningful residuals (e.g., from a fitted model). Did you have anything particular in mind for this model-specific aspect? I think it would make more sense in the context of a regression model, but Arquero does not at the moment provide statistical modeling support.

**Comment by dan-reznik** [comment]
Jeff your functional modularization (not to mention eliminating
redundancies across packages) makes sense.

My requests are essentially motivated by pedagogical needs. When arquero
supports out of the box Spearman and/or R^2 over two numeric sequences I
can present those to the students without exposing implementation details
(stay focused on concepts).

Dan

**Comment by jheer** [comment]
Here is an untested example of R^2 calculation, assuming the values you want to predict are in column `y` and the fitted model predictions are in column `f`:

```js
dt.derive({
    res: d => d.y - d.f, // residuals
    dev: d => d.y - op.mean(d.y) // deviation from the mean
  })
  .rollup({
    r2: d => 1 - op.sum(d.res * d.res) / op.sum(d.dev * d.dev)
  })
  .get('r2') // retrieve single summary value, assuming table is ungrouped
```
