### ISSUE TITLE
DataFrame Structure

### ISSUE THREAD

**Issue by amitkaps** [uwdata/arquero#2]
First, this looks amazing and thank you for creating it.

I am could not find a built in method in the api docs to understand the dataframe/table structure that is created. In `R:dplyr` the underlying dataframe/tibble provides a `str` function to see type of each column vector. In `Python:Pandas`, there is `dtypes` method. In `JS:arquero`, the underlying array is 'read as-is' and there is no-requirement/enforcement of a uniform `type` for each column vector. So there is no built in-method to see what is the current column type being worked on?

I can extend it using the built-in extension. Just wanted to confirm that that is the current case.

**Comment by jheer** [comment]
Yes, the "data frame structure" is simply a set of named array-like objects, with no enforced schema. The underlying [Column abstraction involves only a `length` property and `get(row)` method](https://github.com/uwdata/arquero/blob/master/src/table/column.js). That's it! However most built-in functions perform coercion (string methods coerce to strings, date methods to dates, numeric aggregate operations to numbers, _etc_) to help handle unparsed data.

That said, the underlying arrays can of course be typed, and any custom implementations that follow the Column interface can be passed in to the `table()` constructor. You can of course inspect the data to perform type inference however you see fit.

If folks have ideas for adding (opt-in) types or schema information to Arquero, I'd be happy to consider them!
