### ISSUE TITLE
Typescript issue: Selection helpers have incorrect return type 

### ISSUE THREAD

**Issue by David-Factor** [uwdata/arquero#203]
The selection helper functions `not`, `range`, `all` etc don't seem to typecheck when placed inside a `select` verb. Here is the compile error I'm getting:

```
TS2345: Argument of type 'Function' is not assignable to parameter of type 'Select'.
  Type 'Function' is not assignable to type 'RenameMap'.
    Index signature is missing in type 'Function'.

76   .select(aq.not("A", "B"));
             ~~~~~~~~~~~~~~~
```

Perhaps the return type of the selction helpers should be `SelectHelper`  rather than `Function`? 

```
export function not(...selection: any[]): SelectHelper;
```

Thanks for the amazing library by the way!!

**Comment by jheer** [comment]
Thanks for catching the error! v4.8.1 includes updated return types for the selection helpers.
