### ISSUE TITLE
question: Can it handle datasets with thousands of columns?

### ISSUE THREAD

**Issue by srp33** [uwdata/arquero#208]
This looks like an amazing tool. I work with biological datasets that sometimes have 20,000+ columns. Usually the number of rows is small (maybe a few hundred), but sometimes the number of rows is also large. Do you have any sense for what the size limitations are?

Thanks!

**Comment by jheer** [comment]
Yes, the large number of columns should work fine. Here is a simple example notebook operating on 10,000 columns: https://observablehq.com/d/7dc20de3b3a9b2c6

How many rows is "large"? If you are working in the browser, I suspect you'll run into network transfer issues before hitting any fundamental limits with Arquero. Of course, as the tables get bigger, processing times will increase. Let me know if you run into any issues!

**Comment by srp33** [comment]
Thanks! Well, in extreme cases, we could have datasets with 10,000s of columns and millions of rows. But I don't need to worry about those extreme cases for now. Your response assures me that arquero will be a great fit for what I am trying to do. Looking forward to trying it!

**Comment by RandomFractals** [comment]
Hi! I just wanted to complement how fast arquero operations and aggregators are. I started putting together a set of notebooks on Chicago transportation with public data sets form the city of Chicago data portal. Those real world data sets range in 10-50K records and arquero crunches through them really fast based on my prelim. tests so far. 

I will be updating and optimizing them further, but here is a link to that collection for others to explore: 

https://observablehq.com/collection/@randomfractals/transportation
