### ISSUE TITLE
String Too Long error when calling .loadCSV with local 1.3 GB file

### ISSUE THREAD

**Issue by gordonje** [uwdata/arquero#215]
Greetings,

I'm a big fan of this library! Up to this point, I've mostly been using it in Observable. Though, now I'm beginning to do more heavy lifting in Node, which is a relatively new ecosystem for me.

To that end, I'm stuck on an error when trying to load a 1.3 GB csv file, which is stored locally:

```js
const aq = require('arquero');

const data = aq.loadCSV('./path/to/my-file.csv');

```

Which throws the following exception:

```bash
node:buffer:594
    slice: (buf, start, end) => buf.utf8Slice(start, end),
                                    ^

Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:594:37)
    at Buffer.toString (node:buffer:812:14)
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:63:23) {
  code: 'ERR_STRING_TOO_LONG'
}
```

I've tried several different approaches—using async functions, readStreams, etc.—but without success. Can you offer any guidance?

Thank you,

**Comment by jheer** [comment]
Thanks for sharing @gordonje! The core issue is that currently Arquero reads the entire file into memory, then parses it (much like D3, etc, do). This leads to the error you're seeing. Though not yet implemented, it is on my roadmap to add a streaming reader that circumvents this issue.

In the meantime, a "stop gap" option could be to break up your CSV into multiple smaller files. You could then read in each one-by-one and use the `concat()` verb to combine them into a single table.

(Or, you might try your luck with alternative file formats, such as JSON or Apache Arrow.)

**Comment by gordonje** [comment]
@jheer Thanks for your suggestions!

After wringing my hands for a bit, I dived in with Apache Arrow for the first time. Your examples in [this notebook](https://observablehq.com/@uwdata/arquero-and-apache-arrow) were very helpful. I split my csv into smaller files, loaded them all into the same arquero table, then wrote it to my local file system using `.toArrowBuffer()`.

The result: Cut my file size in half and now have no problem fetching in Observable and parsing with arquero. That's 3.1 million rows with 6 columns loading pretty dang fast!

**Comment by josesho** [comment]
Hi @jheer,

Any update on the streaming reader? I have an Arrow file that might reach 5GB in size, and would love to read this directly without having to first the original file into smaller Arrow files.

Thanks!
Joses

**Comment by domoritz** [comment]
Have you considered using duckdb-wasm, which supports arrow and parquet with a virtual file system so it can read only what it needs?
