### ISSUE TITLE
Naming of fold

### ISSUE THREAD

**Issue by fuzzthink** [uwdata/arquero#216]
Wondering about the naming of `fold`. In functional programming, which is highly related to data processing/transformation, it is synonymous to reduce. Here, it's kinda of the opposite, expanding the data size instead of reduction. To me, it is just pivot but to the other direction. Won't `pivotleft` (EDIT: or `reshape`, as the word used in comment in https://github.com/uwdata/arquero#example) make more sense? If so, would you consider having it as an alias to `fold`?

**Comment by jheer** [comment]
Thanks for the question. The name `fold` comes directly from the database research literature. For example, see the [Potter's Wheel](https://www.vldb.org/conf/2001/P381.pdf) and [Wrangler](http://idl.cs.washington.edu/files/2011-Wrangler-CHI.pdf) projects. The same operation has been called `unpivot` in other contexts, whereas in R's `tidyr` it is now called `pivot_longer`.

You are free to add your own aliases as you see fit, for example by using the [extensibility API](https://uwdata.github.io/arquero/api/extensibility#addTableMethod).

**Comment by fuzzthink** [comment]
Thank you for the links.
