### ISSUE TITLE
Support Arquero to SQL query translation.

### ISSUE THREAD

**Issue by domoritz** [uwdata/arquero#22]
It would be awesome if one could convert a query to SQL so that it can run in a database. Would that be feasible or are there some obvious operations that are not easily translated to SQL?

**Comment by jheer** [comment]
Yes! @chanwutk has already taken this on as a project. Some of the required tasks include:

- Serialize Arquero verbs + expressions to an AST. This is already provided by the internal `query(...).toAST()` method!
- Analyze verbs, segment into SQL queries / sub-queries, likely using a SQL-specific intermediate representation / AST format.
- Analyze verbs + expressions to identify unsupported operations (or perform more complex transforms for operations that don't have a clean one-to-one mapping). Note this may be DB-specific in terms of what functions, aggregate functions, etc. are supported by a particular target engine.
- Generate SQL query code for the target DB engine.

In addition, Arquero could provide a convenient API for issuing queries and marshaling query results to return Arquero tables. The [arquero-worker](https://github.com/uwdata/arquero-worker) package suggests one model and starting point for this.

**Comment by domoritz** [comment]
Awesome. I think @tmostak would be very excited to hear this.

**Comment by jheer** [comment]
As we don't plan to support SQL output in the core Arquero package, I'm going to close out this issue. Feedback or requests regarding Arquero query serialization (`Query.toJSON()`, `Query.toAST()`, _etc._) should be raised in new issues. SQL translation is being explored by @chanwutk and others in the [arquero-sql](https://github.com/chanwutk/arquero-sql) repository.
