### ISSUE TITLE
Question: How use tbl.derive with async functions?

### ISSUE THREAD

**Issue by anchit-sadana** [uwdata/arquero#225]
Hi!

I've been using the arquero library for data manipulation at [Hal9](alpha.hal9.ai). I was wondering if there is a way to derive new columns using an async function. I tried doing a `aq.escape(d => {await fn(d.col)` but that does not work because its an await in a non async function. As a work around I tried using `Promise.all` but I could not find an easy way to add an array to the arquero dataframe as new column. Is there a solution to this?

**Comment by jheer** [comment]
Thanks for the question. At present Arquero does not provide any support for `async` operations. You can however add new arrays as additional columns using the `assign` method:

```js
const extendedTable = table.assign({ newCol: await myAsyncArrayGenerator() });
```
