### ISSUE TITLE
op.slice usage

### ISSUE THREAD

**Issue by dleeftink** [uwdata/arquero#227]
I am running into an issue when trying to use op.slice, whether on arrays or strings. The following code:

```
aq.table({ key: [1, 2], value: [['abc','def','ghi'],['jkl','mno']] })
  .derive({label: d => op.slice(d.value,[1,2])})
  .view()
```
derives the original ordering

key | value | label
-- | -- | --
1 | ["abc","def","ghi"] | ["abc","def","ghi"]
2 | ["jkl","mno"] | ["jkl","mno"]

Expected:

key | value | label
-- | -- | --
1 | ["abc","def","ghi"] | ["def","ghi"]
2 | ["jkl","mno"] | ["mno"]

I am also confused by the comma placement in the [documentation](https://uwdata.github.io/arquero/api/op#slice):

`op.slice(sequence[, start, end])`

throwing the 'Unexpected token' error on Observable. When removing the comma, the 'Error: Unsupported expression construct: SequenceExpression' is displayed. I wonder what is going wrong?

**Comment by jheer** [comment]
Hi, the correct syntax is `op.slice(d.value, 1, 2)` _not_ `op.slice(d.value,[1,2])`.

The use of brackets around arguments in the documentation indicates optional arguments (hence the relation to the comma). Though this is a common JS documentation convention I totally see why it can be confusing!

**Comment by dleeftink** [comment]
I see, I got my array notations mixed up. Thanks for clearing this up!
