### ISSUE TITLE
Getting metadata from arquero-generated arrow table

### ISSUE THREAD

**Issue by stopyransky** [uwdata/arquero#228]
Hey, I was recently exploring this great lib and tried to  retrieve 'pandas' metadata from arrow table. 

I tried the following: 

1. load csv file:
`const columnTable = aq.loadCSV(file)`

2. convert to Arrow like so:
```
const uint8Array = columnTable.toArrowBuffer();
const table = Table.from([uint8Array]);
```

Then I wanted to retrieve 'pandas' metadata:

`table.schema.metadata.get('pandas')`

However the metadata map is empty without any entries.

Is there an error in my approach or the metadata is not populated?
How I could retrieve the metadata for an Arrow Table?

Packages imported to project with following versions:
"@apache-arrow/es2015-cjs": "5.0.0"
"arquero": "4.8.4"

**Comment by jheer** [comment]
Hi! I hope you're finding Arquero useful.

By default Arquero does not add any metadata to the generated Arrow table. So whatever is there is only whatever the Arrow JS library provides. A `pandas` metadata object might be added in Python when exporting Arrow from a Pandas table (I don't know for use, I haven't tried), but is not added in JS.

That said, Arrow itself includes its own metadata regarding the column types. You can see examples of accessing such info using the Arrow library in this notebook: https://observablehq.com/@uwdata/arquero-and-apache-arrow

Hope that helps!

p.s. if you want an Arrow table (not just the bytes) you can convert in one step using `columnTable.toArrow()`.

**Comment by stopyransky** [comment]
Thank you for the answer.

I understood that if I want to have a compatibility between arrows generated in python ecosystem then I need to explicitly write 'pandas-like' metadata in JS, which is a bit cumbersome but maintainable. 

Regarding `.toArrow()` usage - I've tried it, however I receive a typescript error saying that generated arrow Table is not the same as in arrow I use (arquero is using own node_modules/apache-arrow types which are not the same as imported apache-arrow package). Both packages are at latest version though (as in my previous msg)

Below the error I get: 

```
Argument of type 'Table<any>' is not assignable to parameter of type 'Table<any> | PromiseLike<Table<any>>'.
  Type 'import(".../node_modules/arquero/node_modules/apache-arrow/table").Table<any>' is not assignable to type 'import(".../node_modules/@apache-arrow/es2015-cjs/table").Table<any>'.
    Types of property 'concat' are incompatible.
```
similar errors appear on AbstractVector.

Is there a way to 'force' arquero to use types of @apache-arrow used in my project? How to unify these types safely?

**Comment by jheer** [comment]
I see, thanks for sharing! I will look into it, but sounds like Arquero and your loaded Arrow library are using different type instances and this is causing incompatibility. (The problem doesn't seem to arise on Observable when using the same import as Arquero: `require('apache-arrow')`, not the es2015-cjs variant.)
