### ISSUE TITLE
Replacing values

### ISSUE THREAD

**Issue by fuzzthink** [uwdata/arquero#231]
`derive` seems to only create new cols, as indicated by the doc. I tried the following to see if it can be used to replace existing value, but it's not giving me what I want.

```js
      .derive({
        ticker: d => d.ticker.replace('.OB', '')
      })
```
Values became all `undefined.OB`

I tried adding `{drop: true }` but that seems to just drop all cols instead.

How can I replace values?

**Comment by fuzzthink** [comment]
This seems to work
```js
      .derive({ ticker: d => op.replace(d.ticker, '.OB', '') })
```

**Comment by jheer** [comment]
Yes, your second example is the correct approach for Arquero.

To explain the behavior of the first example: Arquero's internal compiler interprets _all_ function calls (regardless of preceding object/property identifiers) relative to the `op` object. So the first call actually translates to `op.replace('.OB', '')`, which has incorrect arguments. We can look into providing better error catching and notification for such cases in the future.
