### ISSUE TITLE
Dependence of derive cols

### ISSUE THREAD

**Issue by fuzzthink** [uwdata/arquero#232]
Currently I have the following as separate `derive` since one depend on the other. I'm wondering if combining them under the same `derive` will work and if there are any speedups doing so.

```js
      .derive({
        vol50: aq.rolling(d => op.round(op.average(d.vol)), [-50, 0]),
      })
      .derive({
        rvol: aq.escape(d => round(d.vol / d.vol50, 2)),
      })
```

**Comment by jheer** [comment]
If one derive expression depends on another, they currently must be provided in sequential calls, as you've done here. Combining them into one derive will not work at this point in time.

**Comment by fuzzthink** [comment]
@jheer 
It seems non-dependent derives still can not be in the same derive clause.

In the rolling average example in cookbook, if I add another rolling average in the same clause with different window, the result of the 2nd rolling average is just a copy of the first.
```js
    .derive({
      ra4: aq.rolling(d => op.average(d.x),  [-4, 0]),
      ra2: aq.rolling(d => op.average(d.x), [-2, 0]),
     })
```

**Comment by jheer** [comment]
Ooh, that is definitely a bug. Thank you for catching this!
