### ISSUE TITLE
Arrow generic Compute API functions?

### ISSUE THREAD

**Issue by jakajancar** [uwdata/arquero#240]
Is the idea that arquero will eventually support the Arrow generic [Compute API](https://jorisvandenbossche.github.io/arrow-docs-preview/html-option-1/cpp/compute.html#) or will it stick with it's own op functions?

(somewhat related: does the Compute API even have a text representation/serialization format that is standard/portable between languages? Is this a weird thing to want? :))

**Comment by jheer** [comment]
There is currently no plan in place to support the Compute API. Arquero is its own library and can be used independently of Apache Arrow. As far I know, the Apache Arrow JavaScript project does not support the Compute API at this time. I haven't used the API myself, so I can't really speak beyond that at the moment.

If someone is interested in implementing the API in a way that works with both Arquero and Arrow, I'd be happy to discuss and help. And no, I don't think it is a weird thing to want portability! ;)
