### ISSUE TITLE
Exposing package.json in exports causes warning and is a potential security risk 

### ISSUE THREAD

**Issue by stopyransky** [uwdata/arquero#247]
Hey, Thanks for work on the arquero package, I have found that following line:

 https://github.com/uwdata/arquero/blob/39cf949efce1ccca5e3a197b430d465b2949f1fb/src/index.js#L26

causes warning "Should not import the named export 'version' (reexported as 'version') from default-exporting module (only default export is available soon)" in a browser

and it is a strong no-no for exposing package.json content to the client, helpful [sof thread here](https://stackoverflow.com/questions/64993118/error-should-not-import-the-named-export-version-imported-as-version)

**Comment by volkanunsal** [comment]
This is not just a waning for me. It's a full-on Webpack error that blocks my work. How does one get around it? @stopyransky

**Comment by stopyransky** [comment]
Not really sure what's causing error on webpack for you @volkanunsal, from what you can read on [stackoverflow](https://stackoverflow.com/questions/70298948/how-to-securely-import-version-from-package-json-while-respecting-error-should) the error is not so problematic on webpack v4 but on v5 it is prominent. 
I am working with next.js framework and here it is only console 'warning' but very annoying one. 
IMO an alternative to exporting from package.json could be a global variable defined at build time of the package... Not sure what's is the use case for the exported version value anyway?

**Comment by domoritz** [comment]
I think the solution is to write 

```js
import pkg from '../package.json';
export const version = pkg.version;
```

Can you try https://github.com/uwdata/arquero/pull/258?

**Comment by volkanunsal** [comment]
@domoritz  That's how I patched my own version. I had to manually change the file, but it's an interim solution. It'd be great if this PR were accepted so I don't have to fork the repo.

**Comment by domoritz** [comment]
Great. I'll let @jheer review and merge it then.
