### ISSUE TITLE
Getting the index of the max value per group

### ISSUE THREAD

**Issue by alippai** [uwdata/arquero#250]
I'm trying to do something like:
```
df
.groupby('name')
.derive({ max_pos: (d) => op.indexof(d.value, op.max(d.value)) })
.rollup({ max_pos: (d) => op.any(d.max_pos) })
```
This doesn't really work, can you help me how to achieve the intended behavior?

**Comment by domoritz** [comment]
Can you use argmax instead?

**Comment by alippai** [comment]
Do you mean op.greatest()?
```
df
.groupby('name')
.derive({ max_pos: (d) => op.indexof(d.value, op.greatest(d.value)) })
.rollup({ max_pos: (d) => op.any(d.max_pos) })``` gives me max value 0 and index -1

**Comment by alippai** [comment]
I might be wrong, but the issue is with indexof, the `d.value` in this groupby context doesn't give a sequence / array so it returns with -1 automatically.

**Comment by jheer** [comment]
Arquero does not include an `argmax` aggregate function, and `greatest` is just a synonym for the standard JavaScript `Math.max` -- it is not an aggregate.

You might filter a table to just the max indices. The filter would preserve duplicated max values, so we need another rollup to de-duplicate, for example by keeping just the minimum index for each group.

```js
dt.ungroup().reify() // ensure consistent indexing
  .derive({ index: () => op.row_number() - 1 }) // generate row indices
  .groupby('name')
  .filter(d => d.value === op.max(d.value)) // keep if value matches the group maximum
  .rollup({ indices: op.min('index') }) // retain only the min index value per group
```

**Comment by nachocab** [comment]
@jheer Related to [this](https://github.com/uwdata/arquero/discussions/292)

What if instead of the columns "name" and "indices" I want other aggregated columns? For example

```js
dt.groupby('name') 
  .rollup({
    min: op.min('value'),
    max: op.max('value'),
    yearWhenMax: ???
    yearWhenMin: ???
  })
```
