### ISSUE TITLE
How to filter by an array of specs

### ISSUE THREAD

**Issue by fuzzthink** [uwdata/arquero#251]
I asked this in Discussions few weeks ago with no answers, so posting here in hopes of getting some.

I want to provide an array of `specs`, like

```js
[
  { date: '2020-01-01', val: 'a' },
  { date: '2020-01-01', val: 'b' },
]
```
and filter aq data with these fields such that it will logically be `row.date < spec.date && row.val===spec.val`.

Does anyone know how this can be done?

thank you.

**Comment by jheer** [comment]
See the original discussion post: https://github.com/uwdata/arquero/discussions/244
