### ISSUE TITLE
table.print() should return table to enable chaining

### ISSUE THREAD

**Issue by mhkeller** [uwdata/arquero#286]
Currently if you do:

```js
table
  .select('col1', 'col2', 'col3')
  .print()
```

You'll see your table in the console. But you can't continue chaining operations. This would be useful to check on the result of an operation before continuing onto the next like so.

```js
table
  .select('col1', 'col2', 'col3')
  .print()
  .groupBy('col1')
  .pivot('col2', 'col3')
  .print()
```

I haven't studied the source code too in-depth but something like `return this` at the end of this function would work: https://github.com/uwdata/arquero/blob/d1721929c64fafdaa3e40ff24ed14993fb7cf417/src/table/table.js#L289

**Comment by jheer** [comment]
That seems reasonable to me! Added in #289.

**Comment by mhkeller** [comment]
Thanks!
