### ISSUE TITLE
Citation for academic paper

### ISSUE THREAD

**Issue by cabreraalex** [uwdata/arquero#287]
Was wondering if there was a prefered way to cite Arquero when used for an academic project/publication.

**Comment by jheer** [comment]
There is no publication about Arquero, so for the time being the website is probably the best reference. Here is some BibTeX you might use:

```
@misc{arquero,
  author = {Jeffrey Heer},
  title = {Arquero: Query processing and transformation of array-backed data tables},
  howpublished = {\url{https://uwdata.github.io/arquero/}},
  note = {Accessed: 2022-08-12}
}
```

**Comment by cabreraalex** [comment]
Sounds great, thanks!
