### ISSUE TITLE
Bind tables by columns?

### ISSUE THREAD

**Issue by juba** [uwdata/arquero#30]
Is there a way to bind tables by columns, in the same way as `concat` bind them by rows ? 

For the moment the only way I found to do it is with something like : 

```js
let tmp1 = dt1.derive({ tmp: op.row_number() });
let tmp2 = dt2.derive({ tmp: op.row_number() });
tmp1
    .join(tmp2)
    .select(aq.not("tmp"));
```

But maybe there is a simpler way to do it ?

Thanks !

**Comment by jheer** [comment]
You can do this:

``` js
aq.table({ ...t1.columns(), ...t2.columns() })
```

Though maybe a helper method might be helpful?

**Comment by juba** [comment]
Well, this way is not complicated by itself, but I wouldn't have thought of it even after searching a bit in the documentation. So an helper method, for me at least, could definitely be useful.

Many thanks for you answer !

**Comment by jheer** [comment]
I've updated the [`table()` documentation](https://uwdata.github.io/arquero/api/#table) to include an example of binding columns together into a new table instance.
