### ISSUE TITLE
Verb to drop columns by name?

### ISSUE THREAD

**Issue by mhkeller** [uwdata/arquero#324]
I didn't see this in the docs. Is there a verb or other method to drop columns similar to Underscore's [`omit`](https://underscorejs.org/#omit)?

**Comment by jcmkk3** [comment]
Check out the selection helpers. You should be able to use `aq.not`. https://uwdata.github.io/arquero/api/#not

**Comment by mhkeller** [comment]
Awesome thanks!

```js
table.select(aq.not('colB', 'colC'))
```
