### ISSUE TITLE
browserlink doesn't work anymore?

### ISSUE THREAD

**Issue by fabiusz85** [uwdata/arquero#359]
on https://www.npmjs.com/package/arquero?activeTab=readme 

states that for browserusage the tag <script src="https://cdn.jsdelivr.net/npm/arquero@latest"></script> is used. 

however since version 6.0.0 this doesn't work anymore.

entering https://cdn.jsdelivr.net/npm/arquero@latest or 
https://cdn.jsdelivr.net/npm/arquero@6.0.0 in a browser
 gets you. "Failed to resolve the requested file."

![Screenshot 2024-07-29 124209](https://github.com/user-attachments/assets/4ceacb14-f4cf-4133-86c9-6a490a3a33c3)

however the older version https://cdn.jsdelivr.net/npm/arquero@5.4.1 still works

**Comment by jheer** [comment]
Thanks for sharing. While I investigate further, it looks like these slightly longer links do work:
- https://cdn.jsdelivr.net/npm/arquero@latest/dist/arquero.min.js
- https://cdn.jsdelivr.net/npm/arquero@6.0.0/dist/arquero.min.js

**Comment by domoritz** [comment]
The problem might be the exports. https://publint.dev/arquero@6.0.0 doesn't flag anything obvious.

**Comment by jheer** [comment]
Fixed by #360

**Comment by fabiusz85** [comment]
thanks ;-)
