### ISSUE TITLE
Documentation lists function `table.transform()` but it doesn't exist

### ISSUE THREAD

**Issue by mz8i** [uwdata/arquero#376]
See here: https://idl.uw.edu/arquero/api/table#transform and as in title: the documentation suggests that there is a function on the table type called `transform()`, but the link to source points to the file `/src/table/column-table.js` which has since been refactored/renamed, and I couldn't find a similar function in the current source.

I'm guessing the function was removed due to being a rather simple wrapper around something one can code themselves (though coming from tidyverse land, it did actually catch my attention when reading the docs for the first time, as a simple out-of-the-box way to execute an array of transformations on a table). In any case, the docs should be updated to reflect the removal. Thanks for the great library!

**Comment by jheer** [comment]
Thank you for catching this. Yes, this method was removed in recent major version changes. We will update the docs!
