### ISSUE TITLE
Cryptic SyntaxError when passing only one argument to `lookup`

### ISSUE THREAD

**Issue by mz8i** [uwdata/arquero#379]
Running the following code:

```ts
const a = aq.from([
    {A: 'a1', B: 'b1'},
    {A: 'a2', B: 'b2'}
])

const b = aq.from([
    {B: 'b1', C: 'c1'},
    {B: 'b2', C: 'c2'}
])

const c = a.lookup(b);
```

most intuitively, I would have expected this to infer the natural default for the `values` argument (which would be all columns apart from the one that is specified/inferred as the `on` argument) and yield a result equivalent to:
```ts
aq.from([
    {A: 'a1', B: 'b1', C: 'c1'},
    {A: 'a2', B: 'b2', C: 'c2'}
])
```

Instead, a SyntaxError is raised, presumably because the library internals generate invalid syntax due to an empty list of expressions passed in.

Please consider:
- allowing using `lookup` with only one argument, or
- improving the docs to specify that at least one expression is required (especially as the `...values` rest argument comes after `on` which in the TypeScript typings is marked as optional, so it's easy to assume that everything apart from `other` is optional)

**Comment by jheer** [comment]
Thanks for the issue! I've added changes to make lookup keys and values optional in #380.

**Comment by mz8i** [comment]
Amazing, thank you!
