### ISSUE TITLE
Easier moving average in windowed operations?

### ISSUE THREAD

**Issue by vorbei** [uwdata/arquero#4]
Recently I'm doing some COVID-19 stats trying to utilize Arquero lib. 
Most of my operations are perfectly ported to Arquero APIs and worked well.
One of my key complaint is the lack of easy moving average operations.

My current version is like:

`
  .derive({
    moving_death_7: d =>
      (op.lag(d.death, 1) +
        op.lag(d.death, 2) +
        op.lag(d.death, 3) +
        op.lag(d.death, 4) +
        op.lag(d.death, 5) +
        op.lag(d.death, 6) +
        op.lag(d.death, 0)) /
      7
  })
`

It's currently unable to use for loops, and it looks awkward a bit. If I want to change to a 14d moving average, it will look even worse. Am I doing it wrong?

**Comment by jheer** [comment]
Hi! All aggregate operations can be used in rolling window query calculations, like so:

`aq.derive({ moving_average: aq.rolling(d =>  op.average(d.value), [-13, 0]) })`

The second argument to the [`rolling()` helper](https://uwdata.github.io/arquero/api/#rolling) defines the window frame. Above is an example for a 14-day moving average. For more examples, please see https://observablehq.com/@uwdata/arquero-cookbook

**Comment by fuzzthink** [comment]
@jheer How do I combine `op.lag` to `table.derive({ moving_average: aq.rolling(d => op.average(d.value), [-13, 0]) })` to not include current row's value?
