### ISSUE TITLE
doc typos

### ISSUE THREAD

**Issue by ericemc3** [uwdata/arquero#41]
I noticed what i think are few minor typos in the doc (API reference):

https://uwdata.github.io/arquero/api/verbs
orderby 
table.orderby('a', desc('b'))
=> table.orderby('a', aq.desc('b'))

table.fold(range(5, 8))
=> table.fold(aq.range(5, 8))

https://uwdata.github.io/arquero/api/op
op.includes
index: The integer index to start **searcing** from (default 0).
=> index: The integer index to start **searching** from (default 0).

**Comment by jheer** [comment]
Thanks!
