### ISSUE TITLE
fromCSV autotype: keep leading 0 

### ISSUE THREAD

**Issue by ericemc3** [uwdata/arquero#42]
aq.fromCSV, with option autotype = true, removes leading 0 (as does d3.autotype, unfortunately).

"06075" => 6075
"01" => 1

Could a test on leading 0 be added to avoid string to number conversion here?

I currently fix this with a specific parse option:
`parse: {zipcode: String}`
but it would be simplier not having to care about this, it would allow for writing more generic function to parse CSV files.

**Comment by ericemc3** [comment]
A suggestion could be, for autoType / csv:
```
export default function(input) {
  const value = input.trim();
  let parsed;

  return !value ? null
    : value === 'true' ? true
    : value === 'false' ? false
    : value === 'NaN' ? NaN
    : String(input).substring(0, 1) === '0' ? input   //new test
    : !isNaN(parsed = +value) ? parsed
    : (parsed = parseIsoDate(value, d => new Date(d))) !== value ? parsed
    : input;
}
```

**Comment by jheer** [comment]
I'd prefer not to special case the autoType logic this way, and I'm not convinced the default behavior is "wrong".

Certainly, disabling auto typing is one option, as is providing a custom parser (such as the identity function), like so:

``` js
aq.fromCSV('foo\n00112', { parse: { foo: x => x } })
```

FWIW, R has the same "problem":

``` r
data <- read.csv(text="flim,flam
00112,2.2
1234,3.14")
#   flim flam
# 1  112 2.20
# 2 1234 3.14
```

**Comment by ericemc3** [comment]
Well, then i'll choose autoType = true and mentionning the geografic code i want (for obvious reasons) to preserve in the parse parameter, rather than specifying all numeric variables in my dataset...

Regarding R and reading CSV files, most people actually use the Tidyverse `readr::read_csv` or the `data.tables::fread`, rather than the base R `read.csv`, which is old and slow.

And both take care of leading 0:
1) this is the default behaviour with readr::read_csv:
```
flimflam <- readr::read_csv("flim,flam
                     00112,2.2
                     1234,3.14")
# A tibble: 2 x 2
  flim   flam
  <chr> <dbl>
1 00112  2.2 
2 1234   3.14
```

2) and controllable with a handy `keepLeadingZeros` parameter in data.tables::fread:
```
flimflam <- data.table::fread("flim,flam
                     00112,2.2
                     1234,3.14", keepLeadingZeros = T)
    flim flam
1: 00112 2.20
2:  1234 3.14
```

3) Finally, d3 allows to specify a custom autoType fonction
`d3.csv(myCsvUrl, myAutoTypeFunction)` but the extra conversion csv => objects => arquero table is not my favourite choice.

**Comment by jheer** [comment]
Thanks for the additional context. I'm open to revisiting this later as part of a larger redesign of input file parsing. Right now Arquero follows the D3 autoType model of parsing values individually. We could later add support to enforce a consistent type in a column (e.g., keep the entire column as string values if one value has a leading zero pattern, as in the readr example above).

For now using a custom parser for the specific fields of interest is probably the best solution. We could also consider allowing the `parse` option to be a function, in which case it could be used as a global parser for all columns (re: your point #3).

**Comment by ericemc3** [comment]
Thanks for keeping this in mind!
