### ISSUE TITLE
Reliable way to test if an object is an Arquero table

### ISSUE THREAD

**Issue by juba** [uwdata/arquero#49]
I hope that my question is not too silly, but I wondered what would be a reliable way to test if a given object is an Arquero Table (for example in the case of a function that would apply both to a table and to a d3 array).

I tried to use `obj.constructor.name` but I believe this is not reliable because the result can change from a version to another due to code minimization.

Is there a "good" way to test for this ?

Many thanks !

**Comment by jheer** [comment]
Not silly at all! One option is:

```js
value instanceof aq.internal.ColumnTable
```

This should work fine at the moment, but could fail in the future if additional Table types are introduced.

Another option is [duck typing](https://en.wikipedia.org/wiki/Duck_typing), for example checking for the existence of corresponding methods to see if a value is an "Arquero-compatible" object:

``` js
typeof value.reify === 'function'
```
