### ISSUE TITLE
Why Error: Illegal function call?  and this library seems very limited unable to call general JS code?

### ISSUE THREAD

**Issue by t829702** [uwdata/arquero#5]
```console
Error: Illegal function call: "Date.UTC(d.year, 0, 1)"
```

    aq.table({ year: [2010, 2011, 2012, 2013, 2019, ] })
      .derive({ date: d => Date.UTC(d.year, 0, 1) })
      .view()

**Comment by jheer** [comment]
Arquero reparses and optimizes expressions, and for safety and future portability reasons only allows function calls provided by the `op` object. This is described in the [introduction tutorial](https://observablehq.com/@uwdata/introducing-arquero) and formal documentation will later be added to the Arquero docs.

The full documentation for the `op` object is here: [https://uwdata.github.io/arquero/api/op](https://uwdata.github.io/arquero/api/op), and includes date-time methods.

**Comment by jheer** [comment]
Note that you can also register custom op functions using the top-level `addFunction` method.
