### ISSUE TITLE
Working with date columns

### ISSUE THREAD

**Issue by peterewills** [uwdata/arquero#62]
FIrst off, thanks for building this - it's making my life a lot easier when I work with data in Observable 😄 

I'm having some trouble working with dates. I build a data table via
```javascript
df = aq.from([
  { date: '2020-01-01 00:00:00.000' },
  { date: '2020-01-02 00:00:00.000' }
])
```
I then add a custom function to shift the date forward 30 days, using `moment`:
```javascript
let shiftDateFunc = d => moment(d).add(30, 'days').format()
aq.addFunction("shiftDate", shiftDateFunc)
```
However, when I try to do
```javascript
df.derive({shiftedDate: op.shiftDate('date')})
```
I get an error:
```
Expression parse error: Invalid date
```
Which is surprising, since I can map this function over the _objects_ just fine:
```javascript
df.objects().map(d => shiftDateFunc(d.date)) // succeeds, returns an array of strings
```
Why can I map this function over the object arrays successfully, but it fails when I register it via `addFunction`? In my mental model the success of the former should imply that the latter will also work, but obviously I'm confused about something.

**Comment by jheer** [comment]
How about this instead? (The `op` special syntax with string column names is defined only for aggregate and window functions...)

```js
df.derive({shiftedDate: d => op.shiftDate(d.date)})
```

**Comment by peterewills** [comment]
That did it! Thanks!
