### ISSUE TITLE
New statistical transforms

### ISSUE THREAD

**Issue by ericemc3** [uwdata/arquero#67]
How about adding those (sorted by descending interest for me):
- sample (`table.sample(n)`)
- density (`op.density(field, bandwidth)`),
- regression,
- loess...

I have actually spotted them in vega-lite transforms collection.

**Comment by jheer** [comment]
Arquero already includes a [sample](https://uwdata.github.io/arquero/api/verbs#sample) verb.

For the other transformations, I do not plan to add those to the main Arquero bundle. That said, I'd be happy to later create an additional package (maybe `arquero-statistics`?) that extends Arquero with additional statistical routines. The vega-statistics and vega-regression packages in the [vega/vega](https://github.com/vega/vega) repo would be natural starting points.

**Comment by ericemc3** [comment]
Thank you for the `sample `reminder. And i understand your point of view about extending Arquero. As a matter of fact, i am currently diving into vega-lite-api, which is an extraordinary library as well. I'd like to get a better sense of Arquero/Vega-lite complementarity (but i think i mostly get the point...)
