### ISSUE TITLE
result of table.antijoin is incoherent

### ISSUE THREAD

**Issue by pgte** [uwdata/arquero#69]
I think I found a problem with `table.antijoin()`, which is evidenced if you try to place this file on the arquero's `test` directory and run it with node:

```js
const aq = require('../')
const assert = require('assert')

const tb1 = aq.table({
  id: [1, 2, 3]
})

const tb2 = aq.table({
  id: [1, 2]
})

const tb3 = tb1.antijoin(tb2)

tb3.print()

assert.equal(tb3.numRows(), 1)
assert.equal(tb3.get('id', 0), 3)
```

This fails with the following error:

```
node:assert:119
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: 1 == 3
    at Object.<anonymous> (/Users/pedroteixeira/projects/deci/arquero/test/antijoin.js:17:8)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 1,
  expected: 3,
  operator: '=='
}
```

The output table is:

```
┌─────────┬────┐
│ (index) │ id │
├─────────┼────┤
│    0    │ 3  │
└─────────┴────┘
```

But the assertion fails.

The problem goes away if I reify the result of the antijoin call:

```js
const tb3 = tb1.antijoin(tb2).reify()
```

If you point me to where the problem lays in the code I can try to fix it.

**Comment by jheer** [comment]
This behavior is as intended. The `antijoin` and `semijoin` methods return _filtered tables_, which do not re-index the data. The `get` method operates on row indices. In the case of filtered tables, these index into the original backing data store. To get the valid (unfiltered) row indices, you can use the `table.indices()` method. To copy the unfiltered data into new arrays with 0...nrows indexing, use `reify`.

I will also update the documentation to hopefully make this clearer.
