### ISSUE TITLE
Typings should be fixed

### ISSUE THREAD

**Issue by vsimko** [uwdata/arquero#71]
### Problem
I tried this:
```js
import {table} from "arquero";

const myTable = table({
  x: [1610109901000, 1610109902000, 1610109903000, 1610109904000],
  y: [600, 610, 590, 602]
});
```

I got a warning from IntelliJ (both in javascript and in typescript): **Invalid number of arguments, expected 2** 

This is because the `names` parameter of the `table` function is not marked as optional.
https://github.com/uwdata/arquero/blob/3083ad35841f61da37aeb9f1b0c234cc71ee862c/src/verbs/index.js#L84-L96

### How to fix
Add the following code to your jsdoc: `@param {string[]?} names`

I would also suggest to review the typings of all functions in your code :smile:

**Comment by jheer** [comment]
Thanks. I updated the JSDoc and released v2.1.1.
