### ISSUE TITLE
Update expression parser to support indirect column name references?

### ISSUE THREAD

**Issue by peterewills** [uwdata/arquero#74]
The following code (within an observable notebook cell) runs just fine:
```javascript
{
  let df = aq.from([{ a: 1 }, { a: 2 }]);
  return df.derive({ b: row => row['a'] + 1 }).view(10);
}
```
But if I try and make the column name a variable, it fails:
```javascript
{
  let df = aq.from([{ a: 1 }, { a: 2 }]);
  let col = 'a';
  return df.derive({ b: row => row[col] + 1 }).view(10);
}
```
I suppose I'm just not understanding the scope in which the lambda gets evaluated, or something. What is the right way to use variable names within the lambdas that get passed to `derive`?

Notebook: https://observablehq.com/@pwills/arquero-confusions

**Comment by jcmkk3** [comment]
I think that you need to make `col` a parameter. https://uwdata.github.io/arquero/api/table#params

More information on the limitations of Expressions can be found here: https://uwdata.github.io/arquero/api/expressions#limitations

**Comment by jheer** [comment]
As @jcmkk3 and the linked documentation points out, Arquero table expressions do not support closures (references to variables defined outside the function body). Parameters provide a workaround, though in this case that fails:

`aq.from([{ a: 1 }, { a: 2 }]).params({ col: 'a' }).derive({ b: (d, $) => d[$.col] + 1 })`

The statement above currently throws an error, as Arquero's internal parser expects column references to be direct (not indirect through a variable or other expression). For example, the following fails as well:

`aq.from([{ a: 1 }, { a: 2 }]).derive({ b: d => d['a' + ''] + 1 })`

I will look into expanding the parser's capability. In the meantime, you must reference a column directly by name, **OR** you can workaround this by providing the table expression as a string in which a direct column name is added:

```js
const col = 'a';
aq.from([{ a: 1 }, { a: 2 }]).derive({ b: `d['${col}'] + 1` })
```

All table expressions are mapped to source code strings and then parsed. The example above simply jumps straight to using a string (if no function signature is provided, the row variable defaults to `d`). Of course, using a string literal means that your development or notebook environment will not be able to perform syntax checking, linting, or auto-complete for you.

**Comment by jheer** [comment]
Arquero v2.1.3 includes a fix so that you should now be able to use params and self-contained expressions to specify column name references. The importable [Arquero observable notebook](https://observablehq.com/@uwdata/arquero) has also been updated.

**Comment by peterewills** [comment]
Great! Thanks.

**Comment by john-guerra** [comment]
In case someone falls into this, I fell into trouble when trying to use regular expressions in a derive method that also used closures.

Passing the function as a string didn't work, but using *escape* did solve the problem.

```js
{
  const attr = "tags";
  aq.from([{ tags: "[1,2,3]" }]).derive({
    tags_cleaned: d => op.replace(d.tags, /[\[\]]/g, ""), //works no closure
    tags_cleaned2: `d => op.replace(d["${attr}"], /[\[\]]/g, "")`, // doesn't work, closure
    tags_cleaned3: aq.escape(d => op.replace(d.tags, /[\[\]]/g, "")) // works, closure
    // tags_cleaned3: `d => op.replace(d["${attr}"], new RegExp("/[\[\]]/", "g"), "")` // doesn't run
  });
}
```

Reference: [Expressions in arquero](https://uwdata.github.io/arquero/api/expressions.html), and [escape](https://uwdata.github.io/arquero/api/#escape)

cc @jheer

**Comment by ericemc3** [comment]
This one ?
`tags_cleaned2: aq.escape(d => d[attr].replace(/[\[\]]/g, ""))`

**Comment by ericemc3** [comment]
or
```
  const attr = "tags", r = /[\[\]]/g ;

  return aq.from([{ tags: "[1,2,3]" }]).derive({
    tags_cleaned5: aq.escape(d => d[attr].replace(/[\[\]]/g, "")),
    tags_cleaned6: `d => op.replace(d.${attr}, ${r}, "")`
  })
```
