### ISSUE TITLE
Add head, tail, and/or slice verbs

### ISSUE THREAD

**Issue by bmschmidt** [uwdata/arquero#78]
It is useful to be able to select individual rows by index, including respect for sorting and grouping.

`dplyr` uses `head(n)`, `tail(n)`, and `slice(indices)`.

R does not respect negative indices in slice, but it would be nice to also be to say
table.slice([-1, 0]) to get the last and first elements, in that order, for each group.

The pandas function `nth` has a better name than slice, but only selects a single row per group.

**Comment by ericemc3** [comment]
It looks like these work fine, with respect for sorting and grouping ?
`tb.filter(d => op.row_number() < 10)`
`tb.groupby('groupvar').filter(d => op.row_number() < 10)`

but of course a more compact writing could prove convenient

**Comment by bmschmidt** [comment]
It certainly works, but it's verbose and hard to keep straight for a pretty common operation in exploratory analysis particularly.
E.g., since row_number is one-indexed, that code `tb.filter(d => op.row_number() < 10)` actually returns the first 9 items, not the first 10! And tail operations aren't symmetric with respect to the index put in:`tb.filter(d=>op.row_number() > op.count() - 10` does return 10.

**Comment by ericemc3** [comment]
yes indeed, the tail operation is more complex to write:

`tb.params({nrows: naiss_tb.numRows()}).filter((d,$) => op.row_number() > $.nrows - 10)`
or
```
let nrows = tb.numRows();
tb.filter(d => op.row_number() >= nrows - 10) ;
```

**Comment by jheer** [comment]
I'm open to adding a `slice()` method to tables that provides syntactic sugar over window based filtering (or something more performant for ungrouped tables), followed by a `reify()` call.

The most delicate aspects concern grouped tables. I'm assuming each group should be sliced separately. Still, the ordering of rows in the output would be solely determined by any `orderby` criteria, oblivious to groups.

Following JavaScript conventions, the method could have a `table.slice(start[, stop])` signature, where negative values indicate an offset from the last row of the group. Output tables would retain the `groupby` criteria of the input.

Note that standard JavaScript does not support "inside out" specifications like the `slice(-1, 0)` described above. I'm unconvinced that Arquero should go down that route. An alternative would be to take two slices and concatenate them, or use a non-sugared windowed filter.

How does this sound?

**Comment by bmschmidt** [comment]
I would be satisfied with a slice operator that follows JS slice syntax while respecting (and preserving) group_by. Selection of non-contiguous subsets is not very important and can be done inside `filter` as described above. `tbl.slice(-5)` for `tail(5)` works great.

**Comment by jheer** [comment]
Added `slice()` verb in v2.2.0.
