### ISSUE TITLE
Add sample_frac verb

### ISSUE THREAD

**Issue by bmschmidt** [uwdata/arquero#79]
pandas has `df.sample(frac=1)` and `df.sample(n=1)`; dplyr has `t %>% sample_frac(1)` and `t %>% sample_n(1)`.

Currently the recommended way to do this is either

* `t.sample(t.numRows())` (only on ungrouped tables). 
* `t.sample(() => op.count())`

The first only works on ungrouped tables, and the second is a little wonky--I only found it in the docs by searching if there was an example of bootstrap sampling.

**Comment by jheer** [comment]
With appropriately tailored inputs, the `sample` verb can support the desired behavior, but I agree that it requires a table expression that may not be intuitive to many user.

Adding a new verb that provides syntactic sugar is one option. Another might be to provide a top-level helper function, akin to `aq.bin`, that serves as an expression generator:

```js
t.sample(aq.frac(0.5)) // => t.sample(() => op.round(0.5 * op.count()))
```

Any opinions either way?

**Comment by bmschmidt** [comment]
I prefer `.sample_frac()` over `aq.frac()` just because I usually rely on tab completion to jog my memory about an API.

The lack of named arguments and docstrings in JS means that you have to read the documentation to find the key unless the function name itself makes the purpose clear. As in https://github.com/uwdata/arquero/issues/78 my preference would be to have families of verbs (as with `join`, `join_full`, `join_right`, `join_left`) that offer shortcuts to base methods that might be used in different ways.

Note though that [`dplyr` is headed in the opposite direction](https://dplyr.tidyverse.org/reference/sample_n.html), although most R IDEs will show arguments:

> sample_n() and sample_frac() have been superseded in favour of slice_sample(). While they will not be deprecated in the near future, retirement means that we will only perform critical bug fixes, so we recommend moving to the newer alternative.

> These functions were superseded because we realised it was more convenient to have two mutually exclusive arguments to one function, rather than two separate functions. This also made it to clean up a few other smaller design issues with sample_n()/sample_frac:

**Comment by jheer** [comment]
I hear you. Still, I'm inclined to limit the "surface area" of verbs for a variety of reasons. In an IDE like VS Code, you do see the documentation in situ (including usage examples), but obviously not all JS environments (e.g., Observable) provide that.

**Comment by jheer** [comment]
Added `aq.frac` helped in v2.2.0.
