### ISSUE TITLE
Wrong links in documentation

### ISSUE THREAD

**Issue by bmschmidt** [uwdata/arquero#83]
Extremely minor documentation issue. All the `[Source]` links on the page https://github.com/uwdata/arquero/blob/master/docs/api/verbs.md link to https://github.com/uwdata/arquero/blob/master/src/table/table.js, but the functions aren't actually listed there. The relevant code is actually at (eg) https://github.com/uwdata/arquero/blob/master/src/engine/select.js.

Thanks for the thorough docs, BTW.

**Comment by jheer** [comment]
Thanks, will fix soon. The links used to be correct, but were neglected after a refactoring...

**Comment by jheer** [comment]
Fixed. Thanks again!
