### ISSUE TITLE
Optimize for dictionary-encoded Arrow columns.

### ISSUE THREAD

**Issue by TheNeuralBit** [uwdata/arquero#86]
Arrow JS's compute library has the ability to optimize filter expressions that operate on a dictionary-encoded column. For example if `foo` is a dictionary encoded string column and you're evaluating `foo == "bar"` we first lookup the dictionary index for "bar" and then search for instances of that index. This can make a huge performance improvement, particularly for string columns where UTF-8 decoding is very expensive.

In Arrow I believe we only do it for equality expressions but you can imagine there are many other  expressions that could benefit from such an optimization (`foo in ("bar", "baz")`, lt, gt, ...). I never got a chance to build that out in Arrow, but now that arquero is here it seems like a much better place for it :)

**Comment by jheer** [comment]
Thanks @TheNeuralBit! I've made good progress on this issue in PR #87, which among other things updates Arquero's expression parser and groupby method to optimize dictionary access.

Locally I am able to match ArrowJS performance if I make some adjustments to how Arquero performs table scans, but I need to perform some more experiments to settle on a suitable approach. Perusing the [Arrow source code](https://github.com/apache/arrow/blob/31050a4e7683bfb3c33e51c45bc7b7dbfe06549e/js/src/compute/dataframe.ts#L174) it looks like this may have been an issue for Arrow as well... and in any case with both Arrow and Arquero I see performance degradation across multiple operations that seems to stem from how V8 applies and revokes internal optimizations.

If you have any thoughts or feedback, please share!

**Comment by jheer** [comment]
Arrow optimizations now released in Arquero v2.3.0.
