### ISSUE TITLE
Table view() with sortable columns and lazy browsing

### ISSUE THREAD

**Issue by ericemc3** [uwdata/arquero#89]
table view() method is convenient for showing/checking a slice of rows. I wish it could implement sortable columns and lazy browsing.

As a matter of fact, Observable released yesterday such a component: https://observablehq.com/@observablehq/input-table

I'd love he could operate on arquero/arrow tables (especially combined with a filtering select dropdown).
Would a rapprochement be conceivable?

**Comment by jheer** [comment]
You can already use Observable's `Table` component as-is. For example, given an Arquero table `dt`, you can use `Table(dt.objects())`. It appears `Table` assumes array-of-objects input, but I haven't looked for the source code yet. It does not appear to support `Iterable` input at the moment; if this is added in the future then `Table(dt)` would also work.

While serializing an Arquero table to objects adds some overhead, for most datasets loaded in a browser this shouldn't be all that costly. And you'll still get the benefits of lazy rendering in the `Table` component. If the `Table` supported options for custom accessors, it could access Arquero data directly (without any copies) in the future. Perhaps @mbostock can say more if there is a future roadmap here!

Also, note that Arquero's table `view()` plugin is not part of the main Arquero repo here - it is defined directly in Observable, though it does leverage the built-in `toHTML()` utility. Another future possibility is to update the Arquero `view` method to support lazy rendering, etc, though I would prefer to have interop with the Observable "standard library".

**Comment by ericemc3** [comment]
Thank you, it makes sense, absolutely. I tried dt.objects(), which is practical, except for big arrow tables. I guess, since an arquero table is iterable, make it usable with Observable Table is essentially a matter of identifying/accessing columns

**Comment by jheer** [comment]
I took a look at the source code here: https://github.com/observablehq/inputs

The `Table` function *does* support iterable input (it uses `Array.from` which works fine on an Arquero table). However, it also defaults the column name selection to the `.columns` property of the first argument to `Table` (see https://github.com/observablehq/inputs/blob/main/src/table.js#L10). For Arquero tables, this property is a method that returns an object containing all columns as properties. As a result the `Table` method is "fooled" into thinking we want zero columns shown. You can hack around this (`Table(dt, { columns: dt.columnNames() })`, but that's arguably less convenient than `dt.objects()`.

It is possible we could remove the `.columns()` method from Arquero (it is actually redundant with `.data()`) but that would also necessitate a breaking change and new major version. I would prefer to have the Observable utility do more input verification to avoid the problem. I'll file an issue to see if this behavior can be modified.

**Comment by mbostock** [comment]
I’ll fix this in Observable Inputs today. Thanks for bringing it to my attention! I’m also considering supporting Arquero tables directly (i.e., calling columns() to determine the columns, not ignoring it).

I think it also might be possible to defer converting the iterable to an array until the table needs to be sorted. That is more work but would improve interaction performance if a large table is changing during interaction. Help welcome. :)

**Comment by jheer** [comment]
Fixed by observablehq/inputs#65. Thanks @mbostock!

**Comment by ericemc3** [comment]
Thanks a lot both of you!
