### ISSUE TITLE
Get indices do not seem to respect table order

### ISSUE THREAD

**Issue by stphnthiel** [uwdata/arquero#90]
First of all: Thanks for this great project. It’s so great to finally see a good data wrangling framework in JavaScript land!

I have only worked with Arquero a couple of hours and stumbled upon an unexpected behavior that you might explain somewhere in the docs. Or it might be a bug.

Accessing individual cell values using `.get(..., index)` does not seem to respect re-ordered tables. Here’s an example:

```js
const dt = aq.table({a: [1, 2, 3], b: [4, 5, 6]});

a	b
1	4
2	5
3	6

dt.get("a", 0); // 1

const dto = dt.orderby(aq.desc("a"));

a	b
3	6
2	5
1	4

dto.get("a", 0); // still 1 but expected 3
```

Any idea why that may be the case?

**Comment by stphnthiel** [comment]
I guess I already found the answer myself: [reify](https://uwdata.github.io/arquero/api/verbs#reify)

**Comment by jheer** [comment]
That’s right! The get method is relative to the actual data layout, separate from filtering and ordering. Without calling reify, you can use the indices method to get the sorted and filtered row indices for the table.

**Comment by stphnthiel** [comment]
Found it, thanks! (also for the fast reply)
