### ISSUE TITLE
Support for flatMap or arrayAgg

### ISSUE THREAD

**Issue by niviksha** [uwdata/arquero#93]
Really loving Arquero so far! One thing I constantly run into is the need for a `flatMap` or equivalently SQL `array_agg` operation - Often grouping by a key, I want to collect the values into an array-valued output. I can use Javascript flatMap, but it would be great to have Arquero support this in its native ops

**Comment by niviksha** [comment]
Nevermind, I figured this out! This works perfectly

```
table.groupby('colA').rollup({ array_agg_col: d => op.concat(op.values(d.colB))})
```

**Comment by jheer** [comment]
For anyone who may come across this issue: As v4.0.0, Arquero has an [`array_agg`](https://uwdata.github.io/arquero/api/op#array_agg) aggregate function, whereas the [`values`](https://uwdata.github.io/arquero/api/op#values) method now extracts the values of an object (similar to how [`keys`](https://uwdata.github.io/arquero/api/op#keys) returns its keys).
